(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



AddSuperClass[name_]:=Module[{symb},
symb=UniqueClass[];
CLType[symb]="SuperClass";
CLName[symb]=name;
SuperClassQ[symb]=True;
CLInstanceList[symb]={};
CLAttributeList[symb]={};
SuperClassChildren[symb]={};
symb]


AddClass[name_]:=Module[{symb},
symb=UniqueClass[];
CLType[symb]="Class";
CLName[symb]=name;
SuperClassQ[symb]=False;
CLInstanceList[symb]={};
CLAttributeList[symb]={};
CLClassAttributeList[symb]={};
CLClassAttributeValueList[symb]={};
CLClassAttributeDeterminedList[symb]={};
SuperClassChildren[symb]={};
symb]



AddClass[name_,superClassName_]:=Module[{symb,parentsymb},
symb=UniqueClass[];
CLType[symb]="Class";
CLName[symb]=name;
SuperClassQ[symb]=False;
CLInstanceList[symb]={};
CLAttributeList[symb]={};
CLClassAttributeList[symb]={};
CLClassAttributeValueList[symb]={};
CLClassAttributeDeterminedList[symb]={};
parentsymb=LookUpClass[superClassName];
SuperClassParent[symb]=parentsymb;
SuperClassChildren[symb]={};
SuperClassChildren[parentsymb]=Append[SuperClassChildren[parentsymb],symb];
symb]




UniqueClass[]:=ClassNb+=1


AddPattern[classname_,name_,value_]:=Module[{symb,classsymb},
symb=UniquePattern[];
PatternName[symb]=name;
PatternValue[symb]=value;
PatternClass[symb]=LookUpClass[classname];
PatternClassList[symb]={};
PatternResultList[symb]={};
AddClassAttribute[classname,"instanceList:"<>name]
symb]



UniquePattern[]:=PatternNb+=1


AddAttribute[classname_,attname_,opts___]:=Module[{symb,class,ask,legv,atttype,initvalue,defvalue},
	ask=question /.{opts} /. Options[AddAttribute];
	legv=legalvalues /.{opts} /. Options[AddAttribute];
	atttype=type /.{opts} /. Options[AddAttribute];
	initvalue=initialvalue /.{opts} /. Options[AddAttribute];
	defvalue=defaultvalue /.{opts} /. Options[AddAttribute];
class=LookUpClass[classname];
symb=UniqueAttribute[];
ATTMetaType[symb]="InstanceAttribute";
ATTClass[symb]=class;
ATTName[symb]=attname;
ATTQuestion[symb]=ask;
ATTLegalValues[symb]=legv;
ATTType[symb]=atttype;
ATTInitialValue[symb]=initvalue;
ATTDefaultValue[symb]=defvalue;
ATTRules[symb]={};
CLAttributeList[class]=Append[CLAttributeList[class],symb];
symb]


AddClassAttribute[classname_,attname_,opts___]:=Module[{symb,class,ask,legv,atttype,initvalue,defvalue},
	ask=question /.{opts} /. Options[AddAttribute];
	legv=legalvalues /.{opts} /. Options[AddAttribute];
	atttype=type /.{opts} /. Options[AddAttribute];
	initvalue=initialvalue /.{opts} /. Options[AddAttribute];
	defvalue=defaultvalue /.{opts} /. Options[AddAttribute];
class=LookUpClass[classname];
symb=UniqueAttribute[];
ATTMetaType[symb]="ClassAttribute";
ATTClass[symb]=class;
ATTName[symb]=attname;
ATTQuestion[symb]=ask;
ATTLegalValues[symb]=legv;
ATTType[symb]=atttype;
ATTInitialValue[symb]=initvalue;
ATTDefaultValue[symb]=defvalue;
ATTRules[symb]={};
CLClassAttributeList[class]=Append[CLClassAttributeList[class],symb];
CLClassAttributeValueList[class]=Append[CLClassAttributeValueList[class],"Nil"];
CLClassAttributeDeterminedList[class]=Append[CLClassAttributeDeterminedList[class],False];
symb]


ClassAttributeValue[classname_,attname_]:=
Module[{class=LookUpClass[classname],att=LookUpAttribute[attname],pos},
pos=Position[CLClassAttributeList[class],att][[1,1]];
CLClassAttributeValueList[class][[pos]]]



ConcludeClassAttributeValue[classname_,attname_,value_]:=
Module[{class=LookUpClass[classname],att=LookUpAttribute[attname],pos,lst},
pos=Position[CLClassAttributeList[class],att][[1,1]];
lst=CLClassAttributeValueList[class];
lst[[pos]]=value;
CLClassAttributeValueList[class]=lst;
lst=CLClassAttributeDeterminedList[class];
lst[[pos]]=True;
If[TraceReasoning==True,Print["*** ",attname,"[",classname,"]","  concluded directly = ",value]];
CLClassAttributeDeterminedList[class]=lst]



ClassAttributeDeterminedQ[classname_,attname_]:=
Module[{class=LookUpClass[classname],att=LookUpAttribute[attname],pos},
pos=Position[CLClassAttributeList[class],att][[1,1]];
CLClassAttributeDeterminedList[class][[pos]]]



Options[AddAttribute]={question->0,legalvalues->0,type->"String",initialvalue->"$$NoInitialValue", defaultvalue->"$$NoInitialValue"};


Options[AddClassAttribute]={question->0,legalvalues->0,type->"String",initialvalue->"$$NoInitialValue",
defaultvalue->"$$NoDefaultValue"};


UniqueAttribute[]:=AttributeNb+=1


LookUpClass[classname_]:=Module[{ll=Select[Range[ClassNb],(CLName[#]==classname)&]},
If[Length[ll]==0,Print["LookUpClass; Non existant class: ",classname];Abort[]];
If[Length[ll]>1,Print["LookUpClass; more than one class called : ",classname];Abort[]];
ll[[1]]]


LookUpAttribute[attname_]:=Module[{ll=Select[Range[AttributeNb],(ATTName[#]==attname)&]},
If[Length[ll]==0,Print["LookUpAttribute: Non existant attribute: ",attname];Abort[]];
If[Length[ll]>1,Print["LookUpAttribute: more than one attribute called : ",attname];Abort[]];
ll[[1]]]


LookUpPattern[pattname_]:=Module[{ll=Select[Range[PatternNb],(PatternName[#]==pattname)&]},
If[Length[ll]==0,Print["LookUpPattern: Non existant pattern: ",pattname];Abort[]];
If[Length[ll]>1,Print["LookUpPattern: more than one pattern called : ",pattname];Abort[]];
ll[[1]]]


LookUpInstanciedAttribute[instanceSymb_,attribute_]:=Module[{ll,attsymb},
attsymb=LookUpAttribute[attribute];
ll=Select[Range[InstanciedAttributeNb],(IAInstance[#]==instanceSymb &&IAAttribute[#]==attsymb )&];
If[Length[ll]==0,Print["LookUpPattern: Non existant InstanciedAttribute: ",attribute ,"<instance-",instanceSymb,">"];Abort[]];
If[Length[ll]>1,Print["LookUpPattern: more than one InstanciedAttribute called : ",attribute ,"<instance-",instanceSymb,">"];Abort[]];
ll[[1]]]    (* pourrait s'obtenir par :InstanceAttributeValue[instanceSymb,attsymb] *)


AddBackwardRule[rulename_,premisse_,conclusion_,concludedatt_,classname_]:=Module[{symb,att=LookUpAttribute[concludedatt],varatt},
symb=UniqueBackwardRule[];
BRPremisse[symb]=HoldForm[premisse];
BRConclusion[symb]=HoldForm[conclusion];
varatt=DeterminePremisseVarAttributeList[HoldForm[premisse]];
BRPremisseAttributeList[symb]=varatt[[2]];
BRPremisseInstanceList[symb]=varatt[[1]];
BRConcludedAttribute[symb]=att;
BRClass[symb]=classname;
ATTRules[att]=Append[ATTRules[att],symb];
BRName[symb]=rulename;]


DeterminePremisseVarAttributeList[premisse_]:=Module[{pos1,pos2,pos3,pos4,table1,table2,table3,table4},
pos1=Position[premisse,Unevaluated[V[_,_]]];
pos2=Position[premisse,Unevaluated[Known[_,_]]];
pos3=Position[premisse,Unevaluated[ExistingObject[_,_]]];
pos4=Position[premisse,Unevaluated[ExistingObjectValue[_,_,_,_]]];
table1=Table[{Extract[premisse,pos1[[i]],Hold][[1,1]],Extract[premisse,pos1[[i]],Hold][[1,2]]},{i,1,Length[pos1]}];
table2=Table[{Extract[premisse,pos2[[i]],Hold][[1,1]],Extract[premisse,pos2[[i]],Hold][[1,2]]},{i,1,Length[pos2]}];
table3=Table[{Extract[premisse,pos3[[i]],Hold][[1,1]],"instanceList:"<>Extract[premisse,pos3[[i]],Hold][[1,1]]},{i,1,Length[pos3]}];
table4=Table[{Extract[premisse,pos4[[i]],Hold][[1,1]],"instanceList:"<>Extract[premisse,pos4[[i]],Hold][[1,4]]},{i,1,Length[pos4]}];
Transpose[Union[table1,table2,table3,table4]]
	]


SetAttributes[AddBackwardRule,HoldAll]


UniqueBackwardRule[]:=BackwardRuleNb+=1


AddInstance[classname_,opts___]:=Module[{symb,class,initial},
initial=initialvalues /.{opts} /. Options[AddInstance];
If[Length[initial]>0,If[Length[initial[[1]]]==0,initial={initial}]];
class=LookUpClass[classname];
symb=UniqueInstance[];
INSClass[symb]=class;
CLInstanceList[class]=Append[CLInstanceList[class],symb];
Map[AddInstanciedAttribute[class,symb,#]&,CLAttributeList[class]];
Map[(Module[
{insatt=InstanceAttributeValue[symb,LookUpAttribute[#[[1]]]]},
IAConcluded[insatt]=True;
IAConcludedInitially[insatt]=True;
IAConcludedValue[insatt]=#[[2]]])&,
initial];
symb]


Options[AddInstance]={initialvalues->{}};


UniqueInstance[]:=InstanceNb+=1


AddInstanciedAttribute[class_,instance_,att_]:=Module[{symb},
	symb=UniqueInstanciedAttribute[];
	IAInstance[symb]=instance;
	IAClass[symb]=class;
	IAAttribute[symb]=att;
	InstanceAttributeValue[instance,att]=symb;
	IAConcluded[symb]=False;
	IARuleThatConcluded[symb]=0;
	IAConcludedByBackchaining[symb]=False;
	IAConcludedByQuestion[symb]=False;
	IAConcludedDirectly[symb]=False;
	IAConcludedInitially[symb]=False;
	IAConcludedToDefaultValue[symb]=False;
	IAConcludedValue[symb]=0;
	IASucceededRuleEvent[symb]=0;
	IATriedRules[symb]={};
	If[ATTInitialValue[att]!= "$$NoInitialValue",
	  IAConcluded[symb]=True;
	  IAConcludedValue[symb]=ATTInitialValue[att]];symb]


UniqueInstanciedAttribute[]:=InstanciedAttributeNb+=1


AddSucceededRuleEvent[rule_, instance_,att_,concltype_]:=Module[{symb},
	symb=UniqueSucceededRuleEvent[];
	SREAttribute[symb]=att;
	SREConclusionType[symb]=concltype;
	SREInstance[symb]=instance;
	SRERule[symb]=rule;
symb]


UniqueSucceededRuleEvent[]:=SucceededRuleEventNb+=1


NewKb[]:=Module[{},ClassNb=0;InstanceNb=0;AttributeNb=0;InstanciedAttributeNb=0;BackwardRuleNb=0;SucceededRuleEventNb=0;PatternNb=0;
Clear[CLName,CLInstanceList,CLAttributeList,SuperClassChildren,SuperClassParent];
Clear[ATTClass,ATTName,ATTQuestion,ATTLegalValues,ATTType,ATTInitialValue,ATTDefaultValue,ATTRules];
Clear[CLClassAttributeList,CLClassAttributeValueList,CLClassAttributeDeterminedList];
Clear[PatternName,PatternValue,PatternClassList,PatternResultList];
Clear[BRPremisse,BRConclusion,BRClass,BRName,BRConcludedAttribute,BRPremisseAttributeList,BRPremisseInstanceList];
Clear[INSClass];
Clear[IAInstance,IAClass,IAAttribute,InstanceAttributeValue,IAConcluded,IARuleThatConcluded,IAConcludedByBackchaining,IAConcludedByQuestion,IAConcludedDirectly,IAConcludedInitially,IAConcludedToDefaultValue,IAConcludedValue,IASucceededRuleEvent,IATriedRules];
Clear[SREInstance,SRERule,SREAttribute,SREConclusionType];
Clear[InstanceAttributeValue]]
