(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



DirectorySave=Directory[];
SetDirectory["C:\\Documents and Settings\\ocroissant\\My Documents\\EDA23\\ExpertSystemEDA23\\PayOffConstruction\\Base"];
Get["Creations.m"];
Get["InferenceEngine.m"];
Get["DisplayFunctions.m"];
Get["Why.m"];
SetDirectory[DirectorySave];



NewKb[];
AddClass["Consultation"];


AddAttribute["Consultation","Main"];
AddAttribute["Consultation","Risk Watch Spec"];
AddAttribute["Consultation","Class Of Instrument",question->"What type of instrument is it ?",
			legalvalues->{"Treasury Bond","Treasury Bill","Bond"}];
AddAttribute["Consultation","Pur Coupon",question->"What is the coupon ?"];
AddAttribute["Consultation","Pur Notional",question->"What is the notional ?"];
AddAttribute["Consultation","Day Counting Convention",question->"What is the Day Counting Convention ?",
			legalvalues->{"actual/actual","actual/365","30E/360","30/360","act/act French","business/30 (CalBRL)"}];
AddAttribute["Consultation","Compounding Frequency",question->"What is the Compounding Frequency Convention ?",
			legalvalues->{"ANNU","SEMI","SMP","CONT","DAY"}];
AddAttribute["Consultation","Trade Day Number",
			question->"What is the number of days needed to settle the deal ?"];
AddAttribute["Consultation","Denominated bond in XEU",question->"Is this bond denominated in XEU ?",
			legalvalues->{"Yes","No"}];
AddAttribute["Consultation","Issuer Currency",question->"What is the issuer currency ?",
	legalvalues->{"USD","PTE","FRF","DKK","DEM","CHF","BEF","SEK","NLG","ESP","NZD","HKD","GBP","CAD","AUD","FIM","ITL"}];
AddAttribute["Consultation","Bond Convention",
	question->"Does this bond follow a convention  ?",
	legalvalues->{"Treasury Bond Convention","Treasury Bill Convention","No Convention"}];
AddAttribute["Consultation","Accrued Interest Computation",question->"What kind of  computation of accruals do you want to use ?",legalvalues->{"Regular","Italian Type"}];
AddAttribute["Consultation","Price Quoted in Yield",question->"Is the price of this bond quoted in yield?",
		legalvalues->{"Yes","No"}];
AddAttribute["Consultation","CSV File Name",question->"What is the Name of the CSV File ?",initialvalue->"out.CSV"];
AddAttribute["Consultation","Want create a CSV File",question->"Do you want to create a csv file ?",
		legalvalues->{"Yes","No"}];
AddAttribute["Consultation","CSV Descriptor"];


AddAttribute["Consultation","Instrument/Type"];
AddAttribute["Consultation","Instrument/Name",question->"What is the name of the instrument ?"];
AddAttribute["Consultation","Instrument/Currency",question->"What is the denomination Currency ?",
	legalvalues->{"USD","PTE","FRF","DKK","DEM","CHF","BEF","SEK","NLG","ESP","NZD","HKD","GBP","CAD","AUD","FIM","ITL","XEU"}];
AddAttribute["Consultation","Instrument/Notional"];
AddAttribute["Consultation","Instrument/Maturity Date",question->"What is the Maturity Date ?"];
AddAttribute["Consultation","Instrument/Issue Date",question->"What is the Issue Date ?"];
AddAttribute["Consultation","Instrument/Fixed Coupon Date",question->"What is the Fixed Coupon Date ?"];
AddAttribute["Consultation","Instrument/Coupon Rate",question->"What is the Fixed Coupon Date ?"];
AddAttribute["Consultation","Instrument/Accrual Daycount Basis",question->"What is the Accrual Daycount Basis ?"];
AddAttribute["Consultation","Instrument/State Procedure"];
AddAttribute["Consultation","Instrument/Coupon Generation Method"];
AddAttribute["Consultation","Instrument/Term",question->"What is the Term?"];
AddAttribute["Consultation","Instrument/Business Day Rule"];
AddAttribute["Consultation","Instrument/Spot Price"];
AddAttribute["Consultation","Instrument/Trade day Rule"];
AddAttribute["Consultation","Instrument/Repo Curve",question->"What is the repo curve ?"];
AddAttribute["Consultation","Instrument/Discount Curve",question->"What is the discount curve ?"];
AddAttribute["Consultation","Instrument/RiskMetrics Map Procedure"];
AddAttribute["Consultation","Instrument/Spread Over Yield"];
AddAttribute["Consultation","Instrument/Theoretical Model*"];
AddAttribute["Consultation","Instrument/Market Model*"];
AddAttribute["Consultation","Market Model/Name",question->"What is the name of the market model ?"];
AddAttribute["Consultation","Market Model/Type"];
AddAttribute["Consultation","Market Model/Value"];
AddAttribute["Consultation","Market Model/Price"];
AddAttribute["Consultation","Market Model/Accrued Interest"];
AddAttribute["Consultation","Market Model/Spot Value"];
AddAttribute["Consultation","Market Model/Yield"];
AddAttribute["Consultation","Theoretical Model/Name",question->"What is the name of the theoretical model ?"];
AddAttribute["Consultation","Theoretical Model/Value"];
AddAttribute["Consultation","Theoretical Model/Price"];
AddAttribute["Consultation","Theoretical Model/Type"];
AddAttribute["Consultation","Theoretical Model/Accrued Interest"];
AddAttribute["Consultation","Theoretical Model/Spot Value"];
AddAttribute["Consultation","Theoretical Model/Yield"];


AddBackwardRule["Main determination 1",
		  (Known[CurrentInstance,"Risk Watch Spec"])&&
		(V[CurrentInstance,"Want create a CSV File"]=="Yes"),
	CSVDescriptor[V[CurrentInstance,"Want create a CSV File"],V[CurrentInstance,"CSV File Name"],V[CurrentInstance,"CSV Descriptor"],CurrentInstance];"Done",
	"Main","Consultation"];

AddBackwardRule["Main determination 2",
		  (Known[CurrentInstance,"Risk Watch Spec"])&&
		(V[CurrentInstance,"Want create a CSV File"]=="No"),
	"Good Bye",
	"Main","Consultation"];



h[x_]:=Module[{},Print["%%%%%% Evaluating Rule : val=",x];x]


AddBackwardRule["Rule Treasury Bond 1", 
	(V[CurrentInstance,"Class Of Instrument"]=="Treasury Bond"),
"Treasury Bond Convention",
"Bond Convention","Consultation"];
AddBackwardRule["Rule Treasury Bond 2",
	(V[CurrentInstance,"Class Of Instrument"]=="Treasury Bond")&&
	(Known[CurrentInstance,"Instrument/Currency"])&&
	(Known[CurrentInstance,"Instrument/Maturity Date"])&&
	(Known[CurrentInstance,"Instrument/Issue Date"])&&
	(Known[CurrentInstance,"Instrument/Fixed Coupon Date"])&&
	(Known[CurrentInstance,"Instrument/Term"])&&
	(Known[CurrentInstance,"Market Model/Accrued Interest"])&&
	(Known[CurrentInstance,"Instrument/Accrual Daycount Basis"]),

Conclude[CurrentInstance,"Instrument/Type","Fixed Rate Bond"];
Conclude[CurrentInstance,"Instrument/Notional",StringJoin[ToString[V[CurrentInstance,"Pur Notional"]]," ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Coupon Rate",StringJoin[ToString[V[CurrentInstance,"Pur Coupon"]],"% ",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"]]];
Conclude[CurrentInstance,"Instrument/State Procedure","@cash flow generator"];
Conclude[CurrentInstance,"Instrument/Coupon Generation Method","Backward"];
Conclude[CurrentInstance,"Instrument/Business Day Rule",
		StringJoin["Regular Following 0-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
Conclude[CurrentInstance,"Instrument/Spot Price",StringJoin["98.8281 ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Trade day Rule",StringJoin["Regular Following ",ToString[V[CurrentInstance,"Trade Day Number"]],
										"-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
    Conclude[CurrentInstance,"Instrument/Repo Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/Discount Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/RiskMetrics Map Procedure","@CashFlow riskmetrics map"];
Conclude[CurrentInstance,"Instrument/Spread Over Yield",StringJoin["@implied spread MKT(%CONT ",V[CurrentInstance,"Day Counting Convention"]]];
Conclude[CurrentInstance,"Market Model/Type","Bond Model"];
Conclude[CurrentInstance,"Market Model/Value","@clean to dirty($)"];
Conclude[CurrentInstance,"Market Model/Price","@spot price($)"];
Conclude[CurrentInstance,"Market Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Market Model/Yield",
	StringJoin["bond IRR from value(%",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"],")"]];
Conclude[CurrentInstance,"Theoretical Model/Type","Bond Model"];
Conclude[CurrentInstance,"Theoretical Model/Value","@PV bond($)"];
Conclude[CurrentInstance,"Theoretical Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Theoretical Model/Price","@PV bond less accrued($)"];
Conclude[CurrentInstance,"Theoretical Model/Accrued Interest",V[CurrentInstance,"Market Model/Accrued Interest"]];
Conclude[CurrentInstance,"Theoretical Model/Yield",V[CurrentInstance,"Market Model/Yield"]];
Conclude[CurrentInstance,"CSV Descriptor",{{"Instrument",{"Name","Type","Currency","Maturity Date","Notional","Issue Date","Coupon Rate",
	     "Fixed Coupon Date","State Procedure","Term","Accrual Daycount Basis",
"Coupon Generation Method","Business Day Rule","Spot Price",
"Trade day Rule","Repo Curve","Discount Curve",
"RiskMetrics Map Procedure","Spread Over Yield","Theoretical Model*","Market Model*"}},
{"Market Model",{"Name","Value","Price","Spot Value","Yield","Accrued Interest"}},
{"Theoretical Model",{"Name","Value","Price","Spot Value","Yield","Accrued Interest"}}}],
"Risk Watch Spec","Consultation"];
	


AddBackwardRule["Rule Day Counting Convention 1",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"USD","ESP","NZD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"actual/actual",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"DKK","DEM","CHF","BEF","SEK","NLG"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"30E/360",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 3",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"FRF"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"act/act French",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 4",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"PTE","FIM"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"30/360",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 5",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"GBP","CAD","AUD","ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"actual/365",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 6",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"USD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	"actual/360",
	"Day Counting Convention","Consultation"];
AddBackwardRule["Rule Day Counting Convention 7",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"HKD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	"actual/365",
	"Day Counting Convention","Consultation"];




AddBackwardRule["Rule Compounding Frequency 1",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ESP","CHF","DEM","DKK","BEF","SEK","NLG","FRF","PTE","FIM"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"ANNU",
	"Compounding Frequency","Consultation"];
AddBackwardRule["Rule Compounding Frequency 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"AUD","CAD","GBP","NZD","USD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"SEMI",
	"Compounding Frequency","Consultation"];
AddBackwardRule["Rule Compounding Frequency ",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention")&&
	V[CurrentInstance,"Denominated bond in XEU"]=="Yes",
	"ANNU",
	"Compounding Frequency","Consultation"];
AddBackwardRule["Rule Compounding Frequency ",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention")&&
	V[CurrentInstance,"Denominated bond in XEU"]=="No",
	"SEMI",
	"Compounding Frequency","Consultation"];
AddBackwardRule["Rule Compounding Frequency ",
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	"SMP",
	"Compounding Frequency","Consultation"];


AddBackwardRule["Rule Trade Day Number 1",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"FRF","GBP"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	1,
	"Trade Day Number","Consultation"];
AddBackwardRule["Rule Trade Day Number 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"DEM","NZD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	2,
	"Trade Day Number","Consultation"];
AddBackwardRule["Rule Trade Day Number 3",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"CHF","DKK","BEF","SEK","NLG","FIM","AUD","CAD","USD","ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	3,
	"Trade Day Number","Consultation"];
AddBackwardRule["Rule Trade Day Number 4",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"PTE"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	4,
	"Trade Day Number","Consultation"];
AddBackwardRule["Rule Trade Day Number 5",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ESP"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	7,
	"Trade Day Number","Consultation"];
AddBackwardRule["Rule Trade Day Number 6",
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	1,
	"Trade Day Number","Consultation"];



AddBackwardRule["Rule Instrument/Term 1",
	(BelongTo[V[CurrentInstance,"Compounding Frequency"],{"SEMI"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"6 Months",
	"Instrument/Term","Consultation"];
AddBackwardRule["Rule Instrument/Term 2",
	(BelongTo[V[CurrentInstance,"Compounding Frequency"],{"ANNU"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"1 Years",
	"Instrument/Term","Consultation"];
AddBackwardRule["Rule Instrument/Term 3",
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	"0 Months",
	"Instrument/Term","Consultation"];


AddBackwardRule["Rule Market Model/Accrued Interest 1",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ESP","CHF","DEM","DKK","BEF","SEK","NLG","FRF",
										"PTE","FIM","AUD","CAD","GBP","NZD","USD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"@accrued bond($)",
	"Market Model/Accrued Interest","Consultation"];
AddBackwardRule["Rule Market Model/Accrued Interest 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"@accrued bond+1($)",
	"Market Model/Accrued Interest","Consultation"];
AddBackwardRule["Rule Market Model/Accrued Interest 3",
	(V[CurrentInstance,"Bond Convention"]=="No Convention")&&
	(V[CurrentInstance,"Accrued Interest Computation"]=="Regular"),
	"@accrued bond($)",
	"Market Model/Accrued Interest","Consultation"];
AddBackwardRule["Rule Market Model/Accrued Interest 4",
	(V[CurrentInstance,"Bond Convention"]=="No Convention")&&
	(V[CurrentInstance,"Accrued Interest Computation"]=="Italian Type"),
	"@accrued bond+1($)",
	"Market Model/Accrued Interest","Consultation"];
AddBackwardRule["Rule Market Model/Accrued Interest 5",
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	"@accrued bond($)",
	"Market Model/Accrued Interest","Consultation"];


AddBackwardRule["Rule Instrument/Currency 1",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Denominated bond in XEU"]=="Yes")&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"XEU",
	"Instrument/Currency","Consultation"];
AddBackwardRule["Rule Instrument/Currency 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Denominated bond in XEU"]=="No")&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	V[CurrentInstance,"Issuer Currency"],
	"Instrument/Currency","Consultation"];
AddBackwardRule["Rule Instrument/Currency 3",
	(!BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	 V[CurrentInstance,"Issuer Currency"],
	"Instrument/Currency","Consultation"];
AddBackwardRule["Rule Instrument/Currency 4",
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
	V[CurrentInstance,"Issuer Currency"],
	"Instrument/Currency","Consultation"];


AddBackwardRule["Rule Accrual Daycount Basis 1",
	(!BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	V[CurrentInstance,"Day Counting Convention"],
	"Instrument/Accrual Daycount Basis","Consultation"];
AddBackwardRule["Rule Accrual Daycount Basis 2",
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"ITL"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bond Convention"),
	"30/360 European",
	"Instrument/Accrual Daycount Basis","Consultation"];



AddBackwardRule["Rule  Bond 1", 
	(V[CurrentInstance,"Class Of Instrument"]=="Bond")&&
	(Known[CurrentInstance,"Instrument/Currency"])&&
	(Known[CurrentInstance,"Instrument/Maturity Date"])&&
	(Known[CurrentInstance,"Instrument/Issue Date"])&&
	(Known[CurrentInstance,"Instrument/Fixed Coupon Date"])&&
	(Known[CurrentInstance,"Instrument/Term"])&&
	(Known[CurrentInstance,"Market Model/Accrued Interest"])&&
	(Known[CurrentInstance,"Instrument/Accrual Daycount Basis"]),

Conclude[CurrentInstance,"Instrument/Type","Fixed Rate Bond"];
Conclude[CurrentInstance,"Instrument/Notional",StringJoin[ToString[V[CurrentInstance,"Pur Notional"]]," ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Coupon Rate",StringJoin[ToString[V[CurrentInstance,"Pur Coupon"]],"% ",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"]]];
Conclude[CurrentInstance,"Instrument/State Procedure","@cash flow generator"];
Conclude[CurrentInstance,"Instrument/Coupon Generation Method","Backward"];
Conclude[CurrentInstance,"Instrument/Business Day Rule",
		StringJoin["Regular Following 0-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
Conclude[CurrentInstance,"Instrument/Spot Price",StringJoin["98.8281 ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Trade day Rule",StringJoin["Regular Following ",ToString[V[CurrentInstance,"Trade Day Number"]],
										"-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
    Conclude[CurrentInstance,"Instrument/Repo Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/Discount Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/RiskMetrics Map Procedure","@CashFlow riskmetrics map"];
Conclude[CurrentInstance,"Instrument/Spread Over Yield","@implied spread MKT(%CONT actual/365)"];
Conclude[CurrentInstance,"Market Model/Type","Bond Model"];
Conclude[CurrentInstance,"Market Model/Value","@clean to dirty($)"];
Conclude[CurrentInstance,"Market Model/Price","@spot price($)"];
Conclude[CurrentInstance,"Market Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Market Model/Yield",
	StringJoin["bond IRR from value(%",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"],")"]];
Conclude[CurrentInstance,"Theoretical Model/Type","Bond Model"];
Conclude[CurrentInstance,"Theoretical Model/Value","@PV bond($)"];
Conclude[CurrentInstance,"Theoretical Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Theoretical Model/Price","@PV bond less accrued($)"];
Conclude[CurrentInstance,"Theoretical Model/Accrued Interest",V[CurrentInstance,"Market Model/Accrued Interest"]];
Conclude[CurrentInstance,"Theoretical Model/Yield",V[CurrentInstance,"Market Model/Yield"]];
Conclude[CurrentInstance,"CSV Descriptor",{{"Instrument",{"Name","Type","Currency","Maturity Date","Notional","Issue Date","Coupon Rate",
	     "Fixed Coupon Date","State Procedure","Term","Accrual Daycount Basis",
"Coupon Generation Method","Business Day Rule","Spot Price",
"Trade day Rule","Repo Curve","Discount Curve",
"RiskMetrics Map Procedure","Spread Over Yield","Theoretical Model*","Market Model*"}},
{"Market Model",{"Name","Value","Price","Spot Value","Yield","Accrued Interest"}},
{"Theoretical Model",{"Name","Value","Price","Spot Value","Yield","Accrued Interest"}}}],
"Risk Watch Spec","Consultation"];
	


AddBackwardRule["Rule Treasury Bill 1", 
	(V[CurrentInstance,"Class Of Instrument"]=="Treasury Bill"),
"Treasury Bond Convention",
"Bond Convention","Consultation"];
AddBackwardRule["Rule  Treasury Bill 2", 
	(V[CurrentInstance,"Class Of Instrument"]=="Treasury Bill")&&
	(Known[CurrentInstance,"Instrument/Currency"])&&
	(Known[CurrentInstance,"Instrument/Maturity Date"])&&
	(Known[CurrentInstance,"Instrument/Issue Date"])&&
	(Known[CurrentInstance,"Instrument/Fixed Coupon Date"])&&
	(Known[CurrentInstance,"Instrument/Term"])&&
	(Known[CurrentInstance,"Market Model/Accrued Interest"])&&
	(Known[CurrentInstance,"Market Model/Price"]),

Conclude[CurrentInstance,"Instrument/Type","Treasury Bill"];
Conclude[CurrentInstance,"Instrument/Notional",StringJoin[ToString[V[CurrentInstance,"Pur Notional"]]," ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Coupon Rate",StringJoin[ToString[V[CurrentInstance,"Pur Coupon"]],"% ",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"]]];
Conclude[CurrentInstance,"Instrument/State Procedure","@cash flow generator"];
Conclude[CurrentInstance,"Instrument/Coupon Generation Method","Backward"];
Conclude[CurrentInstance,"Instrument/Business Day Rule",
		StringJoin["Regular Following 0-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
Conclude[CurrentInstance,"Instrument/Spot Price",StringJoin["98.8281 ",V[CurrentInstance,"Instrument/Currency"]]];
Conclude[CurrentInstance,"Instrument/Trade day Rule",StringJoin["Regular Following ",ToString[V[CurrentInstance,"Trade Day Number"]],
										"-day(Cal",V[CurrentInstance,"Issuer Currency"],")"]];
    Conclude[CurrentInstance,"Instrument/Repo Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/Discount Curve",StringJoin["IR",V[CurrentInstance,"Instrument/Currency"],"-Treasury"]];
Conclude[CurrentInstance,"Instrument/RiskMetrics Map Procedure","@CashFlow riskmetrics map"];
Conclude[CurrentInstance,"Instrument/Spread Over Yield","@implied spread MKT(%CONT actual/365)"];
Conclude[CurrentInstance,"Market Model/Type","Bond Model"];
Conclude[CurrentInstance,"Market Model/Value","@clean to dirty($)"];
Conclude[CurrentInstance,"Market Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Market Model/Yield",
	StringJoin["bond IRR from value(%",V[CurrentInstance,"Compounding Frequency"]," ",V[CurrentInstance,"Day Counting Convention"],")"]];
Conclude[CurrentInstance,"Theoretical Model/Type","Bond Model"];
Conclude[CurrentInstance,"Theoretical Model/Value","@PV bond($)"];
Conclude[CurrentInstance,"Theoretical Model/Spot Value","@spot value($)"];
Conclude[CurrentInstance,"Theoretical Model/Price","@PV bond less accrued($)"];
Conclude[CurrentInstance,"Theoretical Model/Accrued Interest",V[CurrentInstance,"Market Model/Accrued Interest"]];
Conclude[CurrentInstance,"Theoretical Model/Yield",V[CurrentInstance,"Market Model/Yield"]];
Conclude[CurrentInstance,"CSV Descriptor",{{"Instrument",{"Name","Type","Currency","Maturity Date","Notional","Issue Date","Coupon Rate",
	     "Fixed Coupon Date","State Procedure","Term",
"Coupon Generation Method","Business Day Rule","Spot Price",
"Trade day Rule","Repo Curve","Discount Curve",
"RiskMetrics Map Procedure","Spread Over Yield","Theoretical Model*","Market Model*"}},
{"Market Model",{"Name","Value","Price","Spot Value","Yield","Accrued Interest"}},
{"Theoretical Model",{"Name","Value","Price","Spot value","Yield","Accrued Interest"}}}],
"Risk Watch Spec","Consultation"];
	


AddBackwardRule["Theoretical Model 1",
	Known[CurrentInstance,"Theoretical Model/Name"],
	V[CurrentInstance,"Theoretical Model/Name"],
"Instrument/Theoretical Model*","Consultation"];


AddBackwardRule["Market Model 1",
	Known[CurrentInstance,"Market Model/Name"],
	V[CurrentInstance,"Market Model/Name"],
"Instrument/Market Model*","Consultation"];


AddBackwardRule["Rule Market Model/Price 1", 
	(V[CurrentInstance,"Price Quoted in Yield"]=="No"),
"@spot price($)",
"Market Model/Price","Consultation"];


AddBackwardRule["Rule Market Model/Price 2", 
	(V[CurrentInstance,"Price Quoted in Yield"]=="Yes"),
"@price given yield($)",
"Market Model/Price","Consultation"];


AddBackwardRule["Price Quoted in Yield 1", 
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"USD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
"Yes",
"Price Quoted in Yield","Consultation"];


AddBackwardRule["Price Quoted in Yield 2", 
	(BelongTo[V[CurrentInstance,"Issuer Currency"],{"HKD"}])&&
	(V[CurrentInstance,"Bond Convention"]=="Treasury Bill Convention"),
"No",
"Price Quoted in Yield","Consultation"];


Print["end of KB"];


CSVDescriptor[flag_,filename_,listofrecords_,ins_]:=Module[{records,nbrecords=Length[listofrecords],rtype,rattlist,nbatt,str="",i,j},
If[flag=="Yes",
	Do[records=listofrecords[[i]];
		rtype=records[[1]];
		rattlist=records[[2]];
		nbatt=Length[rattlist];
		str=str<>V[ins,rtype<>"/"<>"Type"]<>","<>rattlist[[1]];
	Do[str=str<>","<>rattlist[[j]],{j,2,nbatt}];
	str=str<>"\n,";
	str=str<>V[ins,rtype<>"/"<>rattlist[[1]]];
	Do[str=str<>","<>V[ins,rtype<>"/"<>rattlist[[j]]],{j,2,nbatt}];
	   str=str<>"\n";
,{i,1,nbrecords}];
Print["exporting",str];
Export[filename,str,"Text"]]]
