(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



NewKb[];


AddClass["Scenario"];
AddAttribute["Scenario","CurveShifts"]; (* container for the curve shift *)
AddAttribute["Scenario","Scenario Name"];
AddAttribute["Scenario","Scenario Probability"];
AddAttribute["Scenario","Scenario Color"];


AddClass["CurveShift"];
AddAttribute["CurveShift","Scenario Variable"];
AddAttribute["CurveShift","Scenario Start Time"];
AddAttribute["CurveShift","Scenario Attribute"];
AddAttribute["CurveShift","Time Evolution"];
AddAttribute["CurveShift","Time Evolution to Trigger"];
AddAttribute["CurveShift","Trigger Holder"];
AddAttribute["CurveShift","Scenario Shift Rule"];
AddAttribute["CurveShift","Scenario Type"];
AddAttribute["CurveShift","Scenario Replacement Value"];
AddAttribute["CurveShift","Scen Type"];


AddClass["ScenarioSet"];
AddAttribute["ScenarioSet","Scenarios"]; (* a container for the scenarios *)
AddAttribute["ScenarioSet","Scenario Set Name"];


CSVDescriptor[flag_,filename_,listofrecords_]:=Module[{records,nbrecords=Length[listofrecords],rtype,rattlist,nbatt,str="",i,j},
If[flag=="Yes",
	Do[records=listofrecords[[i]];
		rtype=records[[1]];
		rattlist=records[[2]];
		nbatt=Length[rattlist];
		str=str<>V[rtype<>"\\"<>"Type"]<>","<>rattlist[[1]];
	Do[str=str<>","<>rattlist[[j]],{j,2,nbatt}];
	str=str<>"\n,";
	str=str<>V[rtype<>"\\"<>rattlist[[1]]];
	Do[str=str<>","<>V[rtype<>"\\"<>rattlist[[j]]],{j,2,nbatt}];
	   str=str<>"\n";
,{i,1,nbrecords}];
Print["exporting",str];
Export[filename,str,"Text"]]]



